name: Notify Slack on noindex or nofollow in diffs

on:
  pull_request:
    types: [closed]
    branches:
      - staging-delta
      - develop
      - main

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 全ての履歴を取得

      - name: Check diff for 'noindex' or 'nofollow'
        run: |
          # プルリクエストのマージコミットを取得
          MERGE_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}
          # マージコミットの親を取得
          PARENT_SHA=$(git rev-parse $MERGE_COMMIT_SHA^)

          echo "Diff between $PARENT_SHA and $MERGE_COMMIT_SHA"

          # マージコミットの親とマージコミットとの間の差分をチェック
          if git diff $PARENT_SHA $MERGE_COMMIT_SHA -- '*.html' '*.vue' '*.ts' | grep -Ei 'noindex|nofollow'; then
            echo "Found 'noindex' or 'nofollow'"
            FOUND=true
          else
            FOUND=false
          fi
          echo "found=$FOUND" >> $GITHUB_ENV

      - name: Notify Slack if found
        if: env.found == 'true'
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "attachments": [{
                "color": "#36a64f",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "警告: noindex または nofollow が含まれるコミットがマージされました！"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Description:* ${{github.event.pull_request.body }}"
                      }
                    ]
                  },
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "mrkdwn",
                        "text": "Review the changes in the <${{ github.event.pull_request.html_url }}|Pull Request>"
                      }
                    ]
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
