name: Notify Slack on noindex or nofollow in diffs

on:
  pull_request:
    types: [closed]
    branches:
      - staging-delta
      - develop
      - main

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check diff for 'noindex' or 'nofollow'
        run: |
          # マージ前のヘッドコミットを取得
          HEAD_SHA=$(git rev-parse ${{ github.event.pull_request.head.sha }})
          # ベースブランチのマージ直前のコミットを取得
          BASE_SHA=$(git merge-base origin/${{ github.base_ref }} $HEAD_SHA)

          # マージ前のコミットとの差分をチェック
          echo "Diff between $BASE_SHA and $HEAD_SHA"
          if git diff $BASE_SHA $HEAD_SHA -- '*.html' '*.vue' | grep -Ei 'noindex|nofollow'; then
            echo "Found 'noindex' or 'nofollow'"
            FOUND=true
          else
            FOUND=false
          fi
          echo "found=$FOUND" >> $GITHUB_ENV

      - name: Notify Slack if found
        if: env.found == 'true'
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "attachments": [{
                "color": "#ff0000",
                "blocks": [{
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "警告: noindex または nofollow が含まれるコミットがマージされました"
                  }
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
